name: fooderlich
description: a social recipe app to keep track of new dishes, and share with friends.

publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^3.0.1
  provider: ^6.0.3
  flutter_colorpicker: ^1.0.3
  intl: ^0.17.0
  uuid: ^3.0.6
  smooth_page_indicator: ^1.0.0+2
  webview_flutter: ^3.0.4
  url_launcher: ^6.1.5
  shared_preferences: ^2.0.15
  go_router: ^4.3.0
  cupertino_icons: ^1.0.5
  json_annotation: ^4.7.0
  cached_network_image: ^3.2.2
  http: ^0.13.5
  flutter_slidable: ^2.0.0
  flutter_svg: ^1.1.6
  platform: ^3.1.0
  


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  build_runner: ^2.3.2
  json_serializable: ^6.5.4

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/food_pics/
    - assets/magazine_pics/
    - assets/sample_data/
    - assets/profile_pics/
    - assets/fooderlich_assets/